# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lab_4/grpc/cmd.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'lab_4/grpc/cmd.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14lab_4/grpc/cmd.proto\x12\x07\x63ommand\"\x16\n\x03\x43md\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\"\x14\n\x05Reply\x12\x0b\n\x03msg\x18\x01 \x01(\t28\n\x07\x43ommand\x12-\n\x0bSendCommand\x12\x0c.command.Cmd\x1a\x0e.command.Reply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lab_4.grpc.cmd_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CMD']._serialized_start=33
  _globals['_CMD']._serialized_end=55
  _globals['_REPLY']._serialized_start=57
  _globals['_REPLY']._serialized_end=77
  _globals['_COMMAND']._serialized_start=79
  _globals['_COMMAND']._serialized_end=135
# @@protoc_insertion_point(module_scope)
