# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lab_4/grpc/monitor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'lab_4/grpc/monitor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18lab_4/grpc/monitor.proto\x12\nmonitoring\"K\n\nMetricData\x12\x10\n\x08hostname\x18\x01 \x01(\t\x12\x0e\n\x06metric\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\x12\x0c\n\x04time\x18\x04 \x01(\t\"\x1c\n\x0bMetricReply\x12\r\n\x05reply\x18\x01 \x01(\t2N\n\x07Monitor\x12\x43\n\x0cTransmitData\x12\x16.monitoring.MetricData\x1a\x17.monitoring.MetricReply\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lab_4.grpc.monitor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_METRICDATA']._serialized_start=40
  _globals['_METRICDATA']._serialized_end=115
  _globals['_METRICREPLY']._serialized_start=117
  _globals['_METRICREPLY']._serialized_end=145
  _globals['_MONITOR']._serialized_start=147
  _globals['_MONITOR']._serialized_end=225
# @@protoc_insertion_point(module_scope)
