---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: kafka
data:
  base.properties: |
    process.roles=broker,controller
    controller.listener.names=CONTROLLER
    listeners=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
    inter.broker.listener.name=PLAINTEXT
    listener.security.protocol.map=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
    log.dirs=/var/lib/kafka/data
    num.partitions=3
    offsets.topic.replication.factor=2
    transaction.state.log.replication.factor=2
    controller.quorum.bootstrap.servers=kafka-0.kafka-service.kafka.svc.cluster.local:9093,kafka-1.kafka-service.kafka.svc.cluster.local:9093
    controller.quorum.voters=0@kafka-0.kafka-service.kafka.svc.cluster.local:9093,1@kafka-1.kafka-service.kafka.svc.cluster.local:9093
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka
spec:
  clusterIP: None
  ports:
    - name: kafka
      port: 9092
    - name: controller
      port: 9093
    - name: external
      port: 9094
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: kafka
spec:
  serviceName: kafka-service
  replicas: 2
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: apache/kafka:latest
        command: ["sh", "-c"]
        args:
        - |
          NODE_ID=$(hostname | awk -F'-' '{print $2}');
          CLUSTER_ID="uhaGgVSiR3W05yPkn_pKgw";
          cp /kafka/config/base.properties /opt/kafka/config/server.properties;
          echo "node.id=$NODE_ID" >> /opt/kafka/config/server.properties;
          if [ "$NODE_ID" = "0" ]; then
            echo "advertised.listeners=PLAINTEXT://kafka-0.kafka-service.kafka.svc.cluster.local:9092,EXTERNAL://localhost:9094" >> /opt/kafka/config/server.properties;
          else
            echo "advertised.listeners=PLAINTEXT://kafka-1.kafka-service.kafka.svc.cluster.local:9092,EXTERNAL://localhost:9094" >> /opt/kafka/config/server.properties;
          fi
          /opt/kafka/bin/kafka-storage.sh format -t $CLUSTER_ID -c /opt/kafka/config/server.properties
          /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties
        ports:
        - containerPort: 9092
        - containerPort: 9093
        - containerPort: 9094
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/kafka/data
        - name: config
          mountPath: /kafka/config
      volumes:
      - name: config
        configMap:
          name: kafka-config
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: local-path
      resources:
        requests:
          storage: 10Gi

          
